# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'GithubTop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubTop
  pod 'R.swift'
  pod 'PKHUD', '~> 5.0'

  target 'GithubTopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubTopUITests' do
    # Pods for testing
  end

end
